version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: logs
      MYSQL_USER: loguser
      MYSQL_PASSWORD: logpass
    ports:
      - "2223:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "2222:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: loguser
      PMA_PASSWORD: logpass

  log-receiver:
    build: ./log-receiver
    restart: always
    ports:
      - "2220:9999/udp"
      - "2221:5000"
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "2224:9090"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "2225:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  grafana_data:
